### PR TITLE
closes #313

### LINKED ISSUE #313: Username not updating
**Describe the bug**

After updating username, the skeleton loader didn't get away and didn't update the Profile!

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Edit Profile'
3. Update username
4. See an error

**Expected behavior**

it should update the username and the skeleton loader must disspaear!

**Screenshots**

image

### PR DESCRIPTION
**Pull request by gmrzone**
I worked on the userSettingsPage

### CODE REVIEW

**Comment by gmrzone** [comment]
#### Profile Pic Update Action added
#### Modified listUserDetails Action to also include email

File: frontend/src/actions/userActions.js [hunk 1]
```diff
@@ -98,14 +102,15 @@ export const followUser = (username) => async (dispatch, getState) => {
 
 export const updateUserProfile = (userData) => async (dispatch, getState) => {
   try {
-    dispatch({ type: UPDATE_USER_REQUEST });
+    // dispatch({ type: UPDATE_USER_REQUEST });
     let { user } = await usersService.updateUserProfile(userData);
-
+    user.profile.email = user.email;
```
Comment (codyseibert) [inline frontend/src/actions/userActions.js:107]: what is this for?  the API should be returning the full updated user object, we shouldn't need to change an email unless I'm misunderstanding?

Comment (gmrzone) [reply frontend/src/actions/userActions.js:107]: user detail reducer does not save entire user object in state it only save user.profile which does not include email so added a email property.
